# work in progress!
name: pepita
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - Django
    - gunicorn
    - json5
    - matplotlib
    - pandas
    - pmdarima~=2.0
    - plotly
    - scipy~=1.7
    - seaborn~=0.11
    - whitenoise
