name: pepita
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - Django==4.2.4
    - gunicorn==21.2.0
    - json5==0.9.14
    - matplotlib==3.7.2
    - pandas==2.0.3
    - pmdarima==2.0.4
    - plotly==5.16.1
    - scipy==1.7.1
    - seaborn==0.11.2
    - whitenoise==6.5.0
